### PR TITLE
Fix RecentAnimalsContainer and RecentEventsContainer in Homepage, clo…

### LINKED ISSUE #206: Fix RecentAnimalsContainer and RecentEventsContainer in Homepage
After Graphql schema changes these blocks fail to make queries.
Please update according to the last documentation (see Playground. Possibly pagination and query args fault)

Note: Despite some lists are being moved to Redux, these parts should stay pure graphql queries in react component.

### PR DESCRIPTION
**Pull request by pergaliuke**
closes #206

### CODE REVIEW

File: src/components/layout/RecentEventsContainer.tsx [hunk 1]
```diff
@@ -30,12 +26,12 @@ export default function RecentEventsContainer() {
...
         return <p>Error!</p>;
     }
-    if (!data?.events.length || !data.events[0].all?.length) {
+    if (!data?.events.length) {
         // TODO: replace with proper UI elements
         return <p>No data</p>;
     }
 
-    const events = [...data.events[0].all].sort(sortEventsByDate);
+    const events = [...data.events].sort(sortEventsByDate);
```
Comment (rikius) [inline src/components/layout/RecentEventsContainer.tsx:34]: I will avoid sorting data in UI side

**Review by rikius — APPROVED** [review]
