### PR TITLE
#172 Fix errors on the home page displayed for a non-logged in user

### LINKED ISSUE #172: Fix errors on the home page displayed for a non-logged in user
Currently, recent animals and events are displayed on the home page only to a logged in user. Should a non-logged in user be able to see them too? If not, then no error messages (see the picture below) should appear on his/her screen.

image

### PR DESCRIPTION
**Pull request by mantasimkus**
Errors on the home page are now hidden in case a user is not logged in. Resolves #172.

### CODE REVIEW

File: src/pages/Home.tsx [hunk 1]
```diff
@@ -1,18 +1,25 @@
...
 function Home() {
+    const { user } = useAuth0();
+
     return (
         <Fade in timeout={600}>
             <Page>
                 <AppLogoHeader />
-                <RecentAnimalsContainer />
-                <RecentEventsContainer />
+                {user && (
```
Comment (saulyz) [inline src/pages/Home.tsx:17]: I'd use more direct check `const { isAuthenticated } = useAuth0();`
As we have no intention to do something with `user` prop further on. `user` prop here does work, but it is not a clean code.

**Review by saulyz — CHANGES_REQUESTED** [review]

File: src/pages/Home.tsx (hunk 1 above)
Comment (mantasimkus) [reply src/pages/Home.tsx]: Good point! Thank you! I've modified the code ;)

**Review by saulyz — APPROVED** [review]
